PRACTICA CALIDAD DE DATOS

In [30]:
from dotenv import load_dotenv
import os
import pandas as pd
from sqlalchemy import create_engine

load_dotenv()

#conexion a bd
engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
)

In [31]:
empleados     = pd.read_sql("SELECT * FROM empleados", engine)#probe que se puedan obtener los empleados correctamente
empleados #aqui ya tengo y muestro el dataframe

,id_empleado,nombre,puesto,fecha_contratacion,salario,direccion,correo
0,1,Juaan Perez,Gerent,2010-05-10,80000.0,"Calle Reforma #123, Col. Centro",juanperez@softwaresys.com
1,2,Maria Lopéz,Venedorr,None,45000.0,"Av. Insurgentes #456, Col. Roma",marialopez@softwaresys
2,3,Luis Gracia,NULL,2015-03-15,50000.0,"Calle Juarez #78, Col. Del Valle",NaN
3,4,Pedro Hernandéz,Vendedorr,2013-11-20,70000.0,"Blvd. Hidalgo #100, Col. Morelos",pedro@softwaresis.com
4,5,Juan Perez,Gerente,2010-05-10,60000.0,"Calle Reforma #123, Col. Centro",juanperez@softwaresys.com
5,6,Ana Martines,Gerente,2025-01-01,95000.0,"Av. Universidad #999, Col. Polanco",ana@softwaresys..com
6,7,Carlos Ramíres,Secretaría,2016-08-22,50000.0,"Calle Madero #50, Col. Centro",carlosramires@softwaresys.com

Correcion de puestos (errores de ortografia)

In [32]:
#aqui tenemos que ver primero todas las multiples opciones que se tienen registradas
empleados["puesto"].unique()

<StringArray>
['Gerent', 'Venedorr', 'NULL', 'Vendedorr', 'Gerente', 'Secretaría']
Length: 6, dtype: str

In [33]:
#entonces aqui ya entra nuestro criterio clasificando las opciones que tenemos y que valor seria el correcto
mapeo_puestos = {
    'Gerent':      'Gerente',
    'Venedorr':    'Vendedor',
    #en el caso de null no lo puedo indicar en este paso porque no es un error de ortografia, despues se indicara que puesto sera el correcto al caso o casos donde se tiene null
    'Vendedorr':   'Vendedor',
}

In [34]:
empleados['puesto'] = empleados['puesto'].replace(mapeo_puestos) #aqui es donde aplico el mapeo
print("Puestos únicos tras corrección:", empleados['puesto'].unique())

Puestos únicos tras corrección: <StringArray>
['Gerente', 'Vendedor', 'NULL', 'Secretaría']
Length: 4, dtype: str

In [35]:
empleados

,id_empleado,nombre,puesto,fecha_contratacion,salario,direccion,correo
0,1,Juaan Perez,Gerente,2010-05-10,80000.0,"Calle Reforma #123, Col. Centro",juanperez@softwaresys.com
1,2,Maria Lopéz,Vendedor,None,45000.0,"Av. Insurgentes #456, Col. Roma",marialopez@softwaresys
2,3,Luis Gracia,NULL,2015-03-15,50000.0,"Calle Juarez #78, Col. Del Valle",NaN
3,4,Pedro Hernandéz,Vendedor,2013-11-20,70000.0,"Blvd. Hidalgo #100, Col. Morelos",pedro@softwaresis.com
4,5,Juan Perez,Gerente,2010-05-10,60000.0,"Calle Reforma #123, Col. Centro",juanperez@softwaresys.com
5,6,Ana Martines,Gerente,2025-01-01,95000.0,"Av. Universidad #999, Col. Polanco",ana@softwaresys..com
6,7,Carlos Ramíres,Secretaría,2016-08-22,50000.0,"Calle Madero #50, Col. Centro",carlosramires@softwaresys.com

Limpieza de nombres y con ello eliminacion de duplicados

In [36]:
empleados["nombre"].unique()

<StringArray>
[    'Juaan Perez',     'Maria Lopéz',     'Luis Gracia', 'Pedro Hernandéz',
      'Juan Perez',    'Ana Martines',  'Carlos Ramíres']
Length: 7, dtype: str

In [37]:
# Correcciones puntuales conocidas. Basicamente la misma funcion de mapeo como se hizo en puestos
mapeo_nombres = {
    'Juaan Perez':      'Juan Perez',
    'Luis Gracia':      'Luis García',
    'Ana Martines':     'Ana Martínez',
    'Carlos Ramíres':   'Carlos Ramírez',
}

In [38]:
empleados['nombre'] = empleados['nombre'].replace(mapeo_nombres) #aplico el mapeo
empleados #muestro como quedo el dataframe

,id_empleado,nombre,puesto,fecha_contratacion,salario,direccion,correo
0,1,Juan Perez,Gerente,2010-05-10,80000.0,"Calle Reforma #123, Col. Centro",juanperez@softwaresys.com
1,2,Maria Lopéz,Vendedor,None,45000.0,"Av. Insurgentes #456, Col. Roma",marialopez@softwaresys
2,3,Luis García,NULL,2015-03-15,50000.0,"Calle Juarez #78, Col. Del Valle",NaN
3,4,Pedro Hernandéz,Vendedor,2013-11-20,70000.0,"Blvd. Hidalgo #100, Col. Morelos",pedro@softwaresis.com
4,5,Juan Perez,Gerente,2010-05-10,60000.0,"Calle Reforma #123, Col. Centro",juanperez@softwaresys.com
5,6,Ana Martinez,Gerente,2025-01-01,95000.0,"Av. Universidad #999, Col. Polanco",ana@softwaresys..com
6,7,Carlos Ramirez,Secretaría,2016-08-22,50000.0,"Calle Madero #50, Col. Centro",carlosramires@softwaresys.com