PRÁCTICA 2: Aseguramiento de Calidad de Datos en el Sistema Hospital Salud Vital

In [32]:
from dotenv import load_dotenv
import os
import pandas as pd
from sqlalchemy import create_engine

load_dotenv()

#conexion a bd
engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
)

In [33]:
medicos=pd.read_sql("SELECT * FROM medicos", engine)
medicos

,id_medico,nombre_completo,id_especialidad,correo_electronico,nacionalidad
0,1,Sr(a). Alicia Bonilla,1,sr(a)..bonilla@hospitalvital.mx,Estados Unidoss
1,2,Tomás Velázquez Jaimes,5,tomás.jaimes@hospitalvital.mx,Argentina
2,3,Reina Lorena Angulo,3,reina.angulo@hospitalvital.mx,México
3,4,Soledad Trejo,1,soledad.trejo@hospitalvital.mx,España
4,5,Tomás Hermelinda Rosas Guevara,5,tomás.guevara@hospitalvital.mx,
...,...,...,...,...,...
95,96,Ramón Carrasco Bañuelos,3,ramón.bañuelos@hospitalvital.mx,México
96,97,Ing. Eloy Vega,4,ing..vega@hospitalvital.mx,Alemania
97,98,Dr. Daniel Menchaca,3,dr..menchaca@hospitalvital.mx,Argentina
98,99,Lic. Camilo Flórez,2,lic..flórez@hospitalvital.mx,México
99,100,Lic. Aurora Segovia,1,lic..segovia@hospitalvital.mx,Estados Unidos

LIMPIEZA DE MEDICOS

DETECCION ERRORES

In [34]:
print(medicos.shape)
print(medicos.isnull().sum())
print(medicos.dtypes)

(100, 5)
id_medico             0
nombre_completo       0
id_especialidad       0
correo_electronico    0
nacionalidad          0
dtype: int64
id_medico             int64
nombre_completo         str
id_especialidad       int64
correo_electronico      str
nacionalidad            str
dtype: object

In [35]:
# Nacionalidades unicas — aquí veo los typos
medicos['nacionalidad'].value_counts(dropna=False) #me doy cuenta que en mexico hay México y Mexcio. Colombia y colmbia, null, Estados Unidos, Estados Unidoss

nacionalidad
México             36
Estados Unidos     16
Argentina          14
Alemania           11
España              8
Colombia            4
Colmbia             3
Mexcio              3
Estados Unidoss     2
null                2
                    1
Name: count, dtype: int64

In [36]:
# Valores 'null' como texto y nacionalidades vacias
medicos[medicos['nacionalidad'].isin(['null', '']) | medicos['nacionalidad'].isnull()]

,id_medico,nombre_completo,id_especialidad,correo_electronico,nacionalidad
4,5,Tomás Hermelinda Rosas Guevara,5,tomás.guevara@hospitalvital.mx,
44,45,Renato Carmona Espino,6,renato.espino@hospitalvital.mx,null
94,95,Óliver Nájera,3,óliver.nájera@hospitalvital.mx,null

In [37]:
mask = medicos['correo_electronico'].str.contains(r'\(|\)|mtro\.|ing\.|dr\.|lic\.|sra\.', case=False, na=False)
medicos[mask]

,id_medico,nombre_completo,id_especialidad,correo_electronico,nacionalidad
0,1,Sr(a). Alicia Bonilla,1,sr(a)..bonilla@hospitalvital.mx,Estados Unidoss
14,15,Lic. Felix Crespo,3,lic..crespo@hospitalvital.mx,Colmbia
20,21,Mtro. Amanda Arteaga,1,mtro..arteaga@hospitalvital.mx,México
22,23,Sr(a). Bianca Prado,2,sr(a)..prado@hospitalvital.mx,México
25,26,Dr. Jos Uribe,3,dr..uribe@hospitalvital.mx,España
27,28,Mtro. Sofía Casanova,5,mtro..casanova@hospitalvital.mx,Estados Unidos
30,31,Ing. Karla Sanches,3,ing..sanches@hospitalvital.mx,España
33,34,Ing. Clara Menchaca,2,ing..menchaca@hospitalvital.mx,Alemania
34,35,Mtro. Dalia Orozco,6,mtro..orozco@hospitalvital.mx,Mexcio
35,36,Mtro. Rosalia Miramontes,5,mtro..miramontes@hospitalvital.mx,México
36,37,Ing. Óscar Saiz,2,ing..saiz@hospitalvital.mx,Alemania
37,38,Mtro. Martín Alfaro,2,mtro..alfaro@hospitalvital.mx,Estados Unidos
39,40,Mtro. Sonia Amador,4,mtro..amador@hospitalvital.mx,Estados Unidos
40,41,Lic. Gabino Véliz,1,lic..véliz@hospitalvital.mx,Alemania
41,42,Dr. Amelia Vergara,2,dr..vergara@hospitalvital.mx,México
43,44,Lic. Concepción Guerra,3,lic..guerra@hospitalvital.mx,Colombia
47,48,Ing. Mariana Bañuelos,3,ing..bañuelos@hospitalvital.mx,México
51,52,Mtro. Zoé Jaime,6,mtro..jaime@hospitalvital.mx,Argentina
52,53,Lic. Elisa Gurule,6,lic..gurule@hospitalvital.mx,España
56,57,Ing. Juan Ortega,5,ing..ortega@hospitalvital.mx,México
60,61,Mtro. Ramiro Jurado,1,mtro..jurado@hospitalvital.mx,Alemania
69,70,Dr. Oswaldo Archuleta,6,dr..archuleta@hospitalvital.mx,Estados Unidos
73,74,Sr(a). Israel Linares,1,sr(a)..linares@hospitalvital.mx,España
75,76,Lic. Cecilia Santana,1,lic..santana@hospitalvital.mx,México
79,80,Dr. Delia Palomino,4,dr..palomino@hospitalvital.mx,Estados Unidos
89,90,Dr. Estefanía Cepeda,3,dr..cepeda@hospitalvital.mx,Estados Unidos
91,92,Mtro. Linda Ulloa,4,mtro..ulloa@hospitalvital.mx,Argentina
96,97,Ing. Eloy Vega,4,ing..vega@hospitalvital.mx,Alemania
97,98,Dr. Daniel Menchaca,3,dr..menchaca@hospitalvital.mx,Argentina
98,99,Lic. Camilo Flórez,2,lic..flórez@hospitalvital.mx,México
99,100,Lic. Aurora Segovia,1,lic..segovia@hospitalvital.mx,Estados Unidos

ERRRO 1 CORREGIDO NACIONALIDADES INCOSISTENTES

In [38]:
medicos['nacionalidad'] = medicos['nacionalidad'].replace({
    'Mexcio': 'México',
    'Colmbia': 'Colombia',
    'Estados Unidoss': 'Estados Unidos'
})

# verificar que ya no existan
medicos['nacionalidad'].value_counts(dropna=False)

nacionalidad
México            39
Estados Unidos    18
Argentina         14
Alemania          11
España             8
Colombia           7
null               2
                   1
Name: count, dtype: int64

error 2 nulos o cadenas vacias en nacionalidad llenadas por nacionalidad mas comun

In [39]:
# Error 2 — 'null' como texto y cadena vacía → mexico
medicos['nacionalidad'] = medicos['nacionalidad'].replace({'null': 'México', '': 'México'})
#misma consulta que antes pero ya no salieron resultados de nacionalidades con null o cadena vacia
medicos[medicos['nacionalidad'].isin(['null', '']) | medicos['nacionalidad'].isnull()]

Empty DataFrame
Columns: [id_medico, nombre_completo, id_especialidad, correo_electronico, nacionalidad]
Index: []

Error 3: Persona con nombre incompleto (Jos)

In [40]:
medicos["nombre_completo"].unique() #veo de primera instancia que hay un nombre incompleto (Jos Uribe)-> José Uribe

<StringArray>
[             'Sr(a). Alicia Bonilla',             'Tomás Velázquez Jaimes',
                'Reina Lorena Angulo',                      'Soledad Trejo',
     'Tomás Hermelinda Rosas Guevara',                      'Héctor Rendón',
           'Ana María Cotto Quiñónez',                 'Maximiliano Rivera',
               'Jacinto Samuel Colón',         'Indira Jaime Ozuna Cedillo',
      'Noelia Ramiro Caraballo Matos',            'Martha Carlos Jaramillo',
                  'Fernando Cisneros',                 'Amador López Olivo',
                  'Lic. Felix Crespo',   'Reynaldo Humberto Espinal Crespo',
                      'Noelia Robles',                     'Homero Salinas',
             'Aurora Orozco Santiago',                     'Fabiola Galván',
               'Mtro. Amanda Arteaga',   'Miguel Ángel Rubén Rodrígez Lira',
                'Sr(a). Bianca Prado',             'Gabino Josefina Padrón',
         'Amalia Karla Ávalos Vargas',                      'Dr. Jos Uribe',
        'Antonia Judith Santana Raya',               'Mtro. Sofía Casanova',
                 'Beatriz Laura Niño',     'Porfirio Josefina Colón Farías',
                 'Ing. Karla Sanches',              'Amalia Arellano Chapa',
          'Mario Norma Reyes Córdova',                'Ing. Clara Menchaca',
                 'Mtro. Dalia Orozco',           'Mtro. Rosalia Miramontes',
                    'Ing. Óscar Saiz',                'Mtro. Martín Alfaro',
       'Isabel Zacarías Carmona Peña',                 'Mtro. Sonia Amador',
                  'Lic. Gabino Véliz',                 'Dr. Amelia Vergara',
                        'David Soria',             'Lic. Concepción Guerra',
              'Renato Carmona Espino',            'Marcos Martínez Peralta',
             'Liliana Emilia Partida',              'Ing. Mariana Bañuelos',
              'Norma Emilio Valentín',       'Wilfrido Mateo Sotelo Ocampo',
   'Débora María Luisa Tejada Monroy',                    'Mtro. Zoé Jaime',
                  'Lic. Elisa Gurule',      'Porfirio Héctor Garza Luevano',
        'Emilio Minerva Mateo Rosado',         'Rafaél Gerardo Loera Casas',
                   'Ing. Juan Ortega',      'Clemente Gregorio Arias Loera',
         'Javier Quintanilla Hidalgo',                     'Ernesto Ferrer',
                'Mtro. Ramiro Jurado',                'Bianca Sergio Villa',
              'Federico Amador Tamez',              'Teodoro Eugenia Ávila',
         'Liliana Menéndez Rodríquez',               'Citlali Adame Urbina',
               'Lorenzo Úrsula Rolón',                    'Uriel Feliciano',
         'Inés Gonzalo Bahena Burgos',              'Dr. Oswaldo Archuleta',
                  'Lorena Diana Arce',             'Miguel Ángel Escamilla',
         'Alfonso Abril Lugo Vanegas',              'Sr(a). Israel Linares',
                       'Tomás Tórrez',               'Lic. Cecilia Santana',
                  'Georgina Espinoza',              'Isabel Curiel Reynoso',
       'Eduardo Adela Miranda Lucero',                 'Dr. Delia Palomino',
                    'Noelia Menchaca',             'Karla Cadena Escalante',
                 'Mateo Irene Guzmán',           'Francisca Olivera Gracia',
                   'Gabriela Mendoza',         'Rodolfo Renato Alba Ibarra',
       'Eugenio Anel Casanova Rivero', 'Cristobal Leticia Sandoval Márquez',
             'Timoteo Lucero Nazario',               'Dr. Estefanía Cepeda',
                  'Cristian Rentería',                  'Mtro. Linda Ulloa',
                        'Pablo Gamez',               'Rubén Ariadna Sotelo',
                      'Óliver Nájera',            'Ramón Carrasco Bañuelos',
                     'Ing. Eloy Vega',                'Dr. Daniel Menchaca',
                 'Lic. Camilo Flórez',                'Lic. Aurora Segovia']
Length: 100, dtype: str

In [41]:
medicos.loc[medicos['id_medico'] == 26, 'nombre_completo'] = 'José Uribe'

ERROR 4: Prefijos en nombres de medicos

In [42]:
#  quitar prefijos
prefijos = r'^(?:Sr\(a\)\.|Mtro\.|Ing\.|Dr\.|Lic\.)\s*'

medicos['nombre_completo'] = medicos['nombre_completo'].str.replace(
    prefijos, '', regex=True
).str.strip()

# verificar
mask_prefijo = medicos['nombre_completo'].str.contains(prefijos, na=False)
medicos[mask_prefijo]

Empty DataFrame
Columns: [id_medico, nombre_completo, id_especialidad, correo_electronico, nacionalidad]
Index: []

In [43]:
medicos["nombre_completo"].unique()

<StringArray>
[                    'Alicia Bonilla',             'Tomás Velázquez Jaimes',
                'Reina Lorena Angulo',                      'Soledad Trejo',
     'Tomás Hermelinda Rosas Guevara',                      'Héctor Rendón',
           'Ana María Cotto Quiñónez',                 'Maximiliano Rivera',
               'Jacinto Samuel Colón',         'Indira Jaime Ozuna Cedillo',
      'Noelia Ramiro Caraballo Matos',            'Martha Carlos Jaramillo',
                  'Fernando Cisneros',                 'Amador López Olivo',
                       'Felix Crespo',   'Reynaldo Humberto Espinal Crespo',
                      'Noelia Robles',                     'Homero Salinas',
             'Aurora Orozco Santiago',                     'Fabiola Galván',
                     'Amanda Arteaga',   'Miguel Ángel Rubén Rodrígez Lira',
                       'Bianca Prado',             'Gabino Josefina Padrón',
         'Amalia Karla Ávalos Vargas',                         'José Uribe',
        'Antonia Judith Santana Raya',                     'Sofía Casanova',
                 'Beatriz Laura Niño',     'Porfirio Josefina Colón Farías',
                      'Karla Sanches',              'Amalia Arellano Chapa',
          'Mario Norma Reyes Córdova',                     'Clara Menchaca',
                       'Dalia Orozco',                 'Rosalia Miramontes',
                         'Óscar Saiz',                      'Martín Alfaro',
       'Isabel Zacarías Carmona Peña',                       'Sonia Amador',
                       'Gabino Véliz',                     'Amelia Vergara',
                        'David Soria',                  'Concepción Guerra',
              'Renato Carmona Espino',            'Marcos Martínez Peralta',
             'Liliana Emilia Partida',                   'Mariana Bañuelos',
              'Norma Emilio Valentín',       'Wilfrido Mateo Sotelo Ocampo',
   'Débora María Luisa Tejada Monroy',                          'Zoé Jaime',
                       'Elisa Gurule',      'Porfirio Héctor Garza Luevano',
        'Emilio Minerva Mateo Rosado',         'Rafaél Gerardo Loera Casas',
                        'Juan Ortega',      'Clemente Gregorio Arias Loera',
         'Javier Quintanilla Hidalgo',                     'Ernesto Ferrer',
                      'Ramiro Jurado',                'Bianca Sergio Villa',
              'Federico Amador Tamez',              'Teodoro Eugenia Ávila',
         'Liliana Menéndez Rodríquez',               'Citlali Adame Urbina',
               'Lorenzo Úrsula Rolón',                    'Uriel Feliciano',
         'Inés Gonzalo Bahena Burgos',                  'Oswaldo Archuleta',
                  'Lorena Diana Arce',             'Miguel Ángel Escamilla',
         'Alfonso Abril Lugo Vanegas',                     'Israel Linares',
                       'Tomás Tórrez',                    'Cecilia Santana',
                  'Georgina Espinoza',              'Isabel Curiel Reynoso',
       'Eduardo Adela Miranda Lucero',                     'Delia Palomino',
                    'Noelia Menchaca',             'Karla Cadena Escalante',
                 'Mateo Irene Guzmán',           'Francisca Olivera Gracia',
                   'Gabriela Mendoza',         'Rodolfo Renato Alba Ibarra',
       'Eugenio Anel Casanova Rivero', 'Cristobal Leticia Sandoval Márquez',
             'Timoteo Lucero Nazario',                   'Estefanía Cepeda',
                  'Cristian Rentería',                        'Linda Ulloa',
                        'Pablo Gamez',               'Rubén Ariadna Sotelo',
                      'Óliver Nájera',            'Ramón Carrasco Bañuelos',
                          'Eloy Vega',                    'Daniel Menchaca',
                      'Camilo Flórez',                     'Aurora Segovia']
Length: 100, dtype: str

In [44]:
medicos["nombre_completo"].duplicated().any() # confirme que no hay nombres duplicados

np.False_

Error 5: Correos electrónicos mal construidos

In [45]:
import unicodedata

def quitar_acentos(texto):
    return ''.join(
        c for c in unicodedata.normalize('NFD', texto)
        if unicodedata.category(c) != 'Mn'
    )

def reconstruir_correo(nombre):
    partes = nombre.split()
    primer_nombre = quitar_acentos(partes[0].lower())

    if len(partes) == 2:
        primer_apellido = quitar_acentos(partes[1].lower())
    elif len(partes) == 3:
        primer_apellido = quitar_acentos(partes[1].lower())
    elif len(partes) >= 4:
        primer_apellido = quitar_acentos(partes[2].lower())

    return f"{primer_nombre}{primer_apellido}@hospitalvital.mx"

medicos['correo_electronico'] = medicos['nombre_completo'].apply(reconstruir_correo)

# verificar que no queden acentos
medicos[['nombre_completo', 'correo_electronico']].head(20)

                     nombre_completo                  correo_electronico
0                     Alicia Bonilla      aliciabonilla@hospitalvital.mx
1             Tomás Velázquez Jaimes     tomasvelazquez@hospitalvital.mx
2                Reina Lorena Angulo        reinalorena@hospitalvital.mx
3                      Soledad Trejo       soledadtrejo@hospitalvital.mx
4     Tomás Hermelinda Rosas Guevara         tomasrosas@hospitalvital.mx
5                      Héctor Rendón       hectorrendon@hospitalvital.mx
6           Ana María Cotto Quiñónez           anacotto@hospitalvital.mx
7                 Maximiliano Rivera  maximilianorivera@hospitalvital.mx
8               Jacinto Samuel Colón      jacintosamuel@hospitalvital.mx
9         Indira Jaime Ozuna Cedillo        indiraozuna@hospitalvital.mx
10     Noelia Ramiro Caraballo Matos    noeliacaraballo@hospitalvital.mx
11           Martha Carlos Jaramillo       marthacarlos@hospitalvital.mx
12                 Fernando Cisneros   fernandocisneros@hospitalvital.mx
13                Amador López Olivo        amadorlopez@hospitalvital.mx
14                      Felix Crespo        felixcrespo@hospitalvital.mx
15  Reynaldo Humberto Espinal Crespo    reynaldoespinal@hospitalvital.mx
16                     Noelia Robles       noeliarobles@hospitalvital.mx
17                    Homero Salinas      homerosalinas@hospitalvital.mx
18            Aurora Orozco Santiago       auroraorozco@hospitalvital.mx
19                    Fabiola Galván      fabiolagalvan@hospitalvital.mx

PACIENTES

In [46]:
pacientes=pd.read_sql("SELECT * FROM pacientes", engine)
pacientes

,id_paciente,nombre_completo,fecha_nacimiento,genero,correo_electronico,nacionalidad
0,1,Wilfrido Pacheco Urbina,None,F,wilfrido.pacheco@hospitalvital.mx,México
1,2,Alejandro Rentería Bueno,None,M,alejandro.rentería@hospitalvital.mx,México
2,3,Ignacio Hernádez Mejía,1945-01-07,M,ignacio.hernádez@hotmail.com,México
3,4,Karina Serrano Abreu,2018-10-01,M,karina.serrano@hospitalvital.mx,México
4,5,Patricia Ríos,1985-06-26,F,patricia.ríos@hospitalvital.mx,Estados Unidos
...,...,...,...,...,...,...
195,196,Olivia Cabán,2017-03-02,M,olivia.cabán@hospitalvital.mx,Chile
196,197,Yuridia Piña Sauceda,1978-06-27,F,,México
197,198,Aida Naranjo,1971-04-12,M,aida.naranjo@hotmail.com,Chile
198,199,Dolores Gallegos Mondragón,1995-06-04,F,dolores.gallegos@hospitalvital.mx,México
199,200,Elisa Gastélum Chapa,1950-05-01,M,elisa.gastélum@gmail.mx,México

In [54]:
pacientes["nacionalidad"].unique()

<StringArray>
[        'México', 'Estados Unidos',      'Argentina',       'Colombia',
         'España',          'Japón',          'Chile',       'Alemania',
        'Francia',         'Italia']
Length: 10, dtype: str

In [55]:
medicos["nacionalidad"].unique()

<StringArray>
['Estados Unidos', 'Argentina', 'México', 'España', 'Alemania', 'Colombia']
Length: 6, dtype: str

In [49]:
pacientes["nombre_completo"].duplicated().any() # no hay duplicados

np.False_

In [58]:
pacientes["fecha_nacimiento"].isnull().sum()

np.int64(25)

In [64]:
# para ver todos sin límite
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pacientes[['id_paciente', 'nombre_completo', 'genero']]

     id_paciente                       nombre_completo genero
0              1               Wilfrido Pacheco Urbina      F
1              2              Alejandro Rentería Bueno      M
2              3                Ignacio Hernádez Mejía      M
3              4                  Karina Serrano Abreu      M
4              5                         Patricia Ríos      F
5              6                 Ana Escobedo Sisneros      M
6              7          Silvia Samaniego Quintanilla      M
7              8                Emilia Jaramillo Ulloa      F
8              9                Graciela Quezada Rubio      F
9             10           Alicia Grijalva Covarrubias      F
10            11                   Pedro Alcaraz Urías      M
11            12                 Aurelio Garza Carrera      F
12            13                      Caridad Corrales      F
13            14               Guillermo Saucedo Laboy      M
14            15        Maximiliano Rodríquez Guerrero      F
15            16                         Pedro Colunga      M
16            17                 Elias Zamudio Sauceda      F
17            18                    Celia Barrios Leal      F
18            19                  Linda Molina Sarabia      F
19            20                   Abelardo Leyva Lugo      F
20            21                          Ricardo Saiz      M
21            22                        Conchita Ramón      F
22            23                   Maximiliano Montaño      F
23            24                   Pedro Tórrez Ocasio      M
24            25                   Inés Esparza Griego      M
25            26          Juan Carlos González Partida      F
26            27                            Ilse Rojas      F
27            28              Judith Coronado Saldivar      F
28            29            Carmen Sandoval Villanueva      F
29            30             Benito Quiñónez Camarillo      F
30            31         María Eugenia Alejandro Colón      F
31            32               Vanesa Correa Benavídez      M
32            33                        Gabino Mireles      F
33            34                  Leonel Blanco Méndez      M
34            35                Oswaldo Olivares Mateo      M
35            36                   Micaela Toro Aranda      F
36            37                         Ángela Gollum      F
37            38                   Susana Loera Gaytán      F
38            39                Aurora Puente Calvillo      F
39            40              Benito Quiroz de la Crúz      M
40            41                Helena Anaya Arredondo      F
41            42                   Anabel Lozada Muñoz      M
42            43        Luis Manuel Concepción Guevara      F
43            44                   Lilia Valles Dueñas      M
44            45                 David del Río Berríos      M
45            46                Juana Guajardo Salinas      F
46            47                  Claudio Gómez Riojas      F
47            48                        Florencia Rico      M
48            49                   Yeni Aguirre Rivero      F
49            50                           Zoé Treviño      F
50            51           Antonia Quintanilla Montaño      F
51            52               Helena Pineda Henríquez      F
52            53               Hermelinda Farías Olivo      M
53            54              Bernabé Granado Olivárez      F
54            55                  Jorge Velasco Lucero      M
55            56                Agustín Ortiz Laureano      M
56            57                    Raúl Arroyo Zelaya      F
57            58                       Gonzalo Godínez      M
58            59                   Jesús Gaona Espinal      M
59            60                  Fidel Chapa Calderón      M
60            61                 Verónica Arenas Mares      F
61            62                 Marcos Aponte Venegas      M
62            63               César Bustamante Lucero      F
63            64                         Linda del Río      F
64            65                César Tirado Navarrete      M
65            66                          Mónica Laboy      F
66            67              Francisco Rosario Lucero      M
67            68                  Camila Rocha Benítez      M
68            69               Espartaco Osorio Valdés      F
69            70                 Aurora Ortega Alcaraz      F
70            71               Omar Castañeda Rentería      M
71            72               Zacarías Iglesias Viera      F
72            73                         Teodoro Nieto      F
73            74           Zeferino González Rodríguez      F
74            75                      Silvano Valentín      F
75            76                  Itzel García Barajas      M
76            77                Marisol Madrid Paredes      F
77            78               Clara Armenta Archuleta      M
78            79              Miguel Carrillo Calderón      M
79            80                       Pablo Cervántez      F
80            81            María Elena Nevárez Toledo      F
81            82                Rodrigo Correa Pedroza      F
82            83                    Berta Saiz Pantoja      M
83            84                 Alonso Nevárez Gamboa      M
84            85                  María Gracia Naranjo      F
85            86                     José Carlos Tovar      F
86            87               Jorge Ballesteros Otero      F
87            88                        Elias Casillas      M
88            89               Aurora Galindo Zambrano      F
89            90              Alejandra Arteaga Merino      F
90            91                        Carmen Vallejo      F
91            92                        Ángela Urrutia      F
92            93               Rodrigo Gálvez Gonzales      F
93            94                     Concepción Ybarra      M
94            95                      Gerónimo Colunga      F
95            96               Paola Henríquez Delgado      M
96            97                   Blanca Alvarez Ceja      M
97            98             Jorge Granados Villalobos      M
98            99                Adriana Delgado Jaimes      F
99           100                   Carmen Pérez Sotelo      F
100          101                   Andrea Rolón Rangel      F
101          102              Nelly Villaseñor Cardona      F
102          103                    Nadia García Armas      F
103          104                 Victoria Soliz Madera      M
104          105           Trinidad Angulo Ballesteros      M
105          106                Karla Polanco Cardenas      F
106          107                María Benavides Blanco      F
107          108                Sandra Cordero Barraza      M
108          109                Gerardo Vigil Ulibarri      F
109          110                  Juana Zambrano Tamez      M
110          111          María Elena Santiago Zedillo      F
111          112                         Berta Carrero      M
112          113                    Uriel Ureña Galván      F
113          114            María Cristina Gil Pedraza      M
114          115                   Ivonne Rendón Ozuna      M
115          116                     Barbara Marroquín      M
116          117              Humberto Herrera Noriega      F
117          118                 Cristian Rojo Barrera      M
118          119                          Arturo Cabán      M
119          120                Beatriz Nieves Cedillo      M
120          121            Ana María Villa Valenzuela      M
121          122                Isaac Casillas Partida      M
122          123                  Wendolin Piña Ávalos      F
123          124                     Ruby Marrero Mora      M
124          125              Reynaldo Sarabia Galindo      F
125          126                Víctor Rosario Garrido      M
126          127              Jerónimo Valadez Nazario      F
127          128                     Camila Leiva Vela      M
128          129                  Luis Miguel Valentín      F
129          130                  Sessa Valdés Alvarez      M
130          131                Sandra Jaramillo Anaya      F
131          132                 Georgina Mares Mojica      M
132          133                       Jerónimo Aguayo      M
133          134                Claudio Valles Pacheco      F
134          135                 Ángela Collado Angulo      M
135          136                   Aurora Tamez Galván      F
136          137              Lourdes Rendón Mondragón      F
137          138               Cristina Negrón Marrero      F
138          139                   Irma Vanegas Ybarra      M
139          140                   Amelia Cortés Cotto      F
140          141                 Amador Bonilla Jurado      M
141          142                      Margarita Pineda      F
142          143            Samuel Quintanilla Pedroza      M
143          144                   Esmeralda Sepúlveda      M
144          145                 Jaime Posada Carranza      F
145          146                     Rosalia Ruiz Soto      M
146          147                        Homero Armenta      M
147          148                 Leonardo Zamudio Baca      F
148          149                         Emilia Madera      F
149          150              Citlali Herrera Longoria      M
150          151                 Carla Aguilar Salinas      F
151          152               Delia Ceballos Olivares      F
152          153                        Estela Sanches      F
153          154                Yolanda Moreno Becerra      M
154          155                   Alma Pulido Almaraz      F
155          156           Araceli Marroquín Velásquez      F
156          157               Renato Palacios Perales      M
157          158                Camila Palacios Alonso      M
158          159                   David Rincón Nájera      F
159          160      Marco Antonio Caraballo Guerrero      F
160          161                 Rolando Pacheco Soria      F
161          162                        Leonardo Marín      M
162          163                  Ivonne García Merino      M
163          164               Araceli Segovia Carrera      M
164          165                Nayeli Esquibel Montes      F
165          166               Verónica Cordero Gracia      M
166          167                   Benjamín Concepción      M
167          168               Elvia Delgadillo Zarate      F
168          169                   Vanesa Benítez Díaz      M
169          170                   Miguel Rivera Valle      M
170          171               Marisol Vallejo Medrano      F
171          172               Ignacio Corona Quiñónez      M
172          173                   Mariano Quintanilla      F
173          174                       Hernán Laureano      M
174          175                   Anabel Mora Sarabia      M
175          176                   Horacio Riojas Razo      M
176          177              Ana Luisa Negrete Llamas      F
177          178          Verónica Bustamante Villegas      F
178          179                 Juan Carlos Ríos Vera      F
179          180                   Alma Rascón Vázquez      M
180          181                  Elena Medina Zedillo      F
181          182                         Mónica Corona      M
182          183  María del Carmen Candelaria Montalvo      M
183          184                Natalia de León Arenas      F
184          185                Marcela Quiñones Soria      M
185          186          Santiago Covarrubias Narváez      M
186          187                 Guillermina Ontiveros      F
187          188                   Ivonne Zamora Ávila      M
188          189                  Vicente Mesa Barraza      M
189          190                 Barbara Valdez Olvera      M
190          191                 Flavio Zavala Cornejo      M
191          192             Ariadna Verduzco Cisneros      F
192          193               Horacio Orosco Ceballos      F
193          194                 Arturo Marín Valdivia      F
194          195               Trinidad Méndez Cavazos      F
195          196                          Olivia Cabán      M
196          197                  Yuridia Piña Sauceda      F
197          198                          Aida Naranjo      M
198          199            Dolores Gallegos Mondragón      F
199          200                  Elisa Gastélum Chapa      M

In [63]:
pacientes[pacientes['fecha_nacimiento'].isnull()][['id_paciente', 'nombre_completo', 'fecha_nacimiento']]

     id_paciente             nombre_completo fecha_nacimiento
0              1     Wilfrido Pacheco Urbina             None
1              2    Alejandro Rentería Bueno             None
16            17       Elias Zamudio Sauceda             None
17            18          Celia Barrios Leal             None
20            21                Ricardo Saiz             None
36            37               Ángela Gollum             None
37            38         Susana Loera Gaytán             None
43            44         Lilia Valles Dueñas             None
60            61       Verónica Arenas Mares             None
74            75            Silvano Valentín             None
88            89     Aurora Galindo Zambrano             None
95            96     Paola Henríquez Delgado             None
102          103          Nadia García Armas             None
113          114  María Cristina Gil Pedraza             None
116          117    Humberto Herrera Noriega             None
126          127    Jerónimo Valadez Nazario             None
129          130        Sessa Valdés Alvarez             None
131          132       Georgina Mares Mojica             None
133          134      Claudio Valles Pacheco             None
134          135       Ángela Collado Angulo             None
136          137    Lourdes Rendón Mondragón             None
137          138     Cristina Negrón Marrero             None
140          141       Amador Bonilla Jurado             None
161          162              Leonardo Marín             None
165          166     Verónica Cordero Gracia             None

 Error 6: Nacionalidad como texto repetido en médicos y pacientes

In [65]:
# Obtener nacionalidades únicas de ambas tablas (ya limpias)
nac_medicos = medicos['nacionalidad'].dropna().unique()
nac_pacientes = pacientes['nacionalidad'].dropna().unique()

todas = pd.Series(list(set(nac_medicos) | set(nac_pacientes))).sort_values().reset_index(drop=True)

nacionalidades = pd.DataFrame({
    'id_nacionalidad': range(1, len(todas) + 1),
    'nombre_nacionalidad': todas
})

print(nacionalidades)

   id_nacionalidad nombre_nacionalidad
0                1            Alemania
1                2           Argentina
2                3               Chile
3                4            Colombia
4                5              España
5                6      Estados Unidos
6                7             Francia
7                8              Italia
8                9               Japón
9               10              México

In [66]:
# Reemplazar en medicos
medicos = medicos.merge(nacionalidades, left_on='nacionalidad', right_on='nombre_nacionalidad', how='left')
medicos = medicos.drop(columns=['nacionalidad', 'nombre_nacionalidad'])

# Reemplazar en pacientes
pacientes = pacientes.merge(nacionalidades, left_on='nacionalidad', right_on='nombre_nacionalidad', how='left')
pacientes = pacientes.drop(columns=['nacionalidad', 'nombre_nacionalidad'])

# verificar
print(medicos.columns.tolist())
print(pacientes.columns.tolist())
print(medicos[['nombre_completo', 'id_nacionalidad']].head(10))
print(pacientes[['nombre_completo', 'id_nacionalidad']].head(10))

['id_medico', 'nombre_completo', 'id_especialidad', 'correo_electronico', 'id_nacionalidad']
['id_paciente', 'nombre_completo', 'fecha_nacimiento', 'genero', 'correo_electronico', 'id_nacionalidad']
                  nombre_completo  id_nacionalidad
0                  Alicia Bonilla                6
1          Tomás Velázquez Jaimes                2
2             Reina Lorena Angulo               10
3                   Soledad Trejo                5
4  Tomás Hermelinda Rosas Guevara               10
5                   Héctor Rendón               10
6        Ana María Cotto Quiñónez                5
7              Maximiliano Rivera                1
8            Jacinto Samuel Colón               10
9      Indira Jaime Ozuna Cedillo                6
                nombre_completo  id_nacionalidad
0       Wilfrido Pacheco Urbina               10
1      Alejandro Rentería Bueno               10
2        Ignacio Hernádez Mejía               10
3          Karina Serrano Abreu               10
4                 Patricia Ríos                6
5         Ana Escobedo Sisneros               10
6  Silvia Samaniego Quintanilla               10
7        Emilia Jaramillo Ulloa               10
8        Graciela Quezada Rubio               10
9   Alicia Grijalva Covarrubias               10

In [71]:
medicos.head()

,id_medico,nombre_completo,id_especialidad,correo_electronico,id_nacionalidad
0,1,Alicia Bonilla,1,aliciabonilla@hospitalvital.mx,6
1,2,Tomás Velázquez Jaimes,5,tomasvelazquez@hospitalvital.mx,2
2,3,Reina Lorena Angulo,3,reinalorena@hospitalvital.mx,10
3,4,Soledad Trejo,1,soledadtrejo@hospitalvital.mx,5
4,5,Tomás Hermelinda Rosas Guevara,5,tomasrosas@hospitalvital.mx,10

In [70]:
pacientes.head() #si

,id_paciente,nombre_completo,fecha_nacimiento,genero,correo_electronico,id_nacionalidad
0,1,Wilfrido Pacheco Urbina,None,F,wilfrido.pacheco@hospitalvital.mx,10
1,2,Alejandro Rentería Bueno,None,M,alejandro.rentería@hospitalvital.mx,10
2,3,Ignacio Hernádez Mejía,1945-01-07,M,ignacio.hernádez@hotmail.com,10
3,4,Karina Serrano Abreu,2018-10-01,M,karina.serrano@hospitalvital.mx,10
4,5,Patricia Ríos,1985-06-26,F,patricia.ríos@hospitalvital.mx,6

ERROR 7 GENERO INCORRECTO SEGUN NOMBRE DE PACIENTE

In [72]:
correcciones_genero = {
    4: 'F',   # Karina
    6: 'F',   # Ana
    7: 'F',   # Silvia
    12: 'M',  # Aurelio
    15: 'M',  # Maximiliano
    17: 'M',  # Elias
    20: 'M',  # Abelardo
    23: 'M',  # Maximiliano
    25: 'F',  # Inés
    26: 'M',  # Juan Carlos
    30: 'M',  # Benito
    32: 'F',  # Vanesa
    33: 'M',  # Gabino
    42: 'F',  # Anabel
    44: 'F',  # Lilia
    48: 'F',  # Florencia
    53: 'F',  # Hermelinda
    54: 'M',  # Bernabé
    57: 'M',  # Raúl
    63: 'M',  # César
    68: 'F',  # Camila
    69: 'M',  # Espartaco
    72: 'M',  # Zacarías
    73: 'M',  # Teodoro
    74: 'M',  # Zeferino
    75: 'M',  # Silvano
    76: 'F',  # Itzel
    78: 'F',  # Clara
    80: 'M',  # Pablo
    82: 'M',  # Rodrigo
    83: 'F',  # Berta
    86: 'M',  # José Carlos
    87: 'M',  # Jorge
    93: 'M',  # Rodrigo
    94: 'F',  # Concepción
    95: 'M',  # Gerónimo
    96: 'F',  # Paola
    97: 'F',  # Blanca
    104: 'F', # Victoria
    105: 'F', # Trinidad
    108: 'F', # Sandra
    109: 'M', # Gerardo
    110: 'F', # Juana
    112: 'F', # Berta
    113: 'M', # Uriel
    114: 'F', # María Cristina
    115: 'F', # Ivonne
    116: 'F', # Barbara
    117: 'M', # Humberto
    120: 'F', # Beatriz
    121: 'F', # Ana María
    124: 'F', # Ruby
    125: 'M', # Reynaldo
    128: 'F', # Camila
    129: 'M', # Luis Miguel
    132: 'F', # Georgina
    134: 'M', # Claudio
    135: 'F', # Ángela
    139: 'F', # Irma
    144: 'F', # Esmeralda
    145: 'M', # Jaime
    146: 'F', # Rosalia
    148: 'M', # Leonardo
    150: 'F', # Citlali
    154: 'F', # Yolanda
    158: 'F', # Camila
    159: 'M', # David
    160: 'M', # Marco Antonio
    161: 'M', # Rolando
    163: 'F', # Ivonne
    164: 'F', # Araceli
    166: 'F', # Verónica
    169: 'F', # Vanesa
    173: 'M', # Mariano
    175: 'F', # Anabel
    179: 'M', # Juan Carlos
    180: 'F', # Alma
    182: 'F', # Mónica
    183: 'F', # María del Carmen
    185: 'F', # Marcela
    188: 'F', # Ivonne
    196: 'F', # Olivia
    198: 'F', # Aida
    200: 'F', # Elisa
}

for id_pac, genero in correcciones_genero.items():
    pacientes.loc[pacientes['id_paciente'] == id_pac, 'genero'] = genero

# verificar
pacientes[['id_paciente', 'nombre_completo', 'genero']]

     id_paciente                       nombre_completo genero
0              1               Wilfrido Pacheco Urbina      F
1              2              Alejandro Rentería Bueno      M
2              3                Ignacio Hernádez Mejía      M
3              4                  Karina Serrano Abreu      F
4              5                         Patricia Ríos      F
5              6                 Ana Escobedo Sisneros      F
6              7          Silvia Samaniego Quintanilla      F
7              8                Emilia Jaramillo Ulloa      F
8              9                Graciela Quezada Rubio      F
9             10           Alicia Grijalva Covarrubias      F
10            11                   Pedro Alcaraz Urías      M
11            12                 Aurelio Garza Carrera      M
12            13                      Caridad Corrales      F
13            14               Guillermo Saucedo Laboy      M
14            15        Maximiliano Rodríquez Guerrero      M
15            16                         Pedro Colunga      M
16            17                 Elias Zamudio Sauceda      M
17            18                    Celia Barrios Leal      F
18            19                  Linda Molina Sarabia      F
19            20                   Abelardo Leyva Lugo      M
20            21                          Ricardo Saiz      M
21            22                        Conchita Ramón      F
22            23                   Maximiliano Montaño      M
23            24                   Pedro Tórrez Ocasio      M
24            25                   Inés Esparza Griego      F
25            26          Juan Carlos González Partida      M
26            27                            Ilse Rojas      F
27            28              Judith Coronado Saldivar      F
28            29            Carmen Sandoval Villanueva      F
29            30             Benito Quiñónez Camarillo      M
30            31         María Eugenia Alejandro Colón      F
31            32               Vanesa Correa Benavídez      F
32            33                        Gabino Mireles      M
33            34                  Leonel Blanco Méndez      M
34            35                Oswaldo Olivares Mateo      M
35            36                   Micaela Toro Aranda      F
36            37                         Ángela Gollum      F
37            38                   Susana Loera Gaytán      F
38            39                Aurora Puente Calvillo      F
39            40              Benito Quiroz de la Crúz      M
40            41                Helena Anaya Arredondo      F
41            42                   Anabel Lozada Muñoz      F
42            43        Luis Manuel Concepción Guevara      F
43            44                   Lilia Valles Dueñas      F
44            45                 David del Río Berríos      M
45            46                Juana Guajardo Salinas      F
46            47                  Claudio Gómez Riojas      F
47            48                        Florencia Rico      F
48            49                   Yeni Aguirre Rivero      F
49            50                           Zoé Treviño      F
50            51           Antonia Quintanilla Montaño      F
51            52               Helena Pineda Henríquez      F
52            53               Hermelinda Farías Olivo      F
53            54              Bernabé Granado Olivárez      M
54            55                  Jorge Velasco Lucero      M
55            56                Agustín Ortiz Laureano      M
56            57                    Raúl Arroyo Zelaya      M
57            58                       Gonzalo Godínez      M
58            59                   Jesús Gaona Espinal      M
59            60                  Fidel Chapa Calderón      M
60            61                 Verónica Arenas Mares      F
61            62                 Marcos Aponte Venegas      M
62            63               César Bustamante Lucero      M
63            64                         Linda del Río      F
64            65                César Tirado Navarrete      M
65            66                          Mónica Laboy      F
66            67              Francisco Rosario Lucero      M
67            68                  Camila Rocha Benítez      F
68            69               Espartaco Osorio Valdés      M
69            70                 Aurora Ortega Alcaraz      F
70            71               Omar Castañeda Rentería      M
71            72               Zacarías Iglesias Viera      M
72            73                         Teodoro Nieto      M
73            74           Zeferino González Rodríguez      M
74            75                      Silvano Valentín      M
75            76                  Itzel García Barajas      F
76            77                Marisol Madrid Paredes      F
77            78               Clara Armenta Archuleta      F
78            79              Miguel Carrillo Calderón      M
79            80                       Pablo Cervántez      M
80            81            María Elena Nevárez Toledo      F
81            82                Rodrigo Correa Pedroza      M
82            83                    Berta Saiz Pantoja      F
83            84                 Alonso Nevárez Gamboa      M
84            85                  María Gracia Naranjo      F
85            86                     José Carlos Tovar      M
86            87               Jorge Ballesteros Otero      M
87            88                        Elias Casillas      M
88            89               Aurora Galindo Zambrano      F
89            90              Alejandra Arteaga Merino      F
90            91                        Carmen Vallejo      F
91            92                        Ángela Urrutia      F
92            93               Rodrigo Gálvez Gonzales      M
93            94                     Concepción Ybarra      F
94            95                      Gerónimo Colunga      M
95            96               Paola Henríquez Delgado      F
96            97                   Blanca Alvarez Ceja      F
97            98             Jorge Granados Villalobos      M
98            99                Adriana Delgado Jaimes      F
99           100                   Carmen Pérez Sotelo      F
100          101                   Andrea Rolón Rangel      F
101          102              Nelly Villaseñor Cardona      F
102          103                    Nadia García Armas      F
103          104                 Victoria Soliz Madera      F
104          105           Trinidad Angulo Ballesteros      F
105          106                Karla Polanco Cardenas      F
106          107                María Benavides Blanco      F
107          108                Sandra Cordero Barraza      F
108          109                Gerardo Vigil Ulibarri      M
109          110                  Juana Zambrano Tamez      F
110          111          María Elena Santiago Zedillo      F
111          112                         Berta Carrero      F
112          113                    Uriel Ureña Galván      M
113          114            María Cristina Gil Pedraza      F
114          115                   Ivonne Rendón Ozuna      F
115          116                     Barbara Marroquín      F
116          117              Humberto Herrera Noriega      M
117          118                 Cristian Rojo Barrera      M
118          119                          Arturo Cabán      M
119          120                Beatriz Nieves Cedillo      F
120          121            Ana María Villa Valenzuela      F
121          122                Isaac Casillas Partida      M
122          123                  Wendolin Piña Ávalos      F
123          124                     Ruby Marrero Mora      F
124          125              Reynaldo Sarabia Galindo      M
125          126                Víctor Rosario Garrido      M
126          127              Jerónimo Valadez Nazario      F
127          128                     Camila Leiva Vela      F
128          129                  Luis Miguel Valentín      M
129          130                  Sessa Valdés Alvarez      M
130          131                Sandra Jaramillo Anaya      F
131          132                 Georgina Mares Mojica      F
132          133                       Jerónimo Aguayo      M
133          134                Claudio Valles Pacheco      M
134          135                 Ángela Collado Angulo      F
135          136                   Aurora Tamez Galván      F
136          137              Lourdes Rendón Mondragón      F
137          138               Cristina Negrón Marrero      F
138          139                   Irma Vanegas Ybarra      F
139          140                   Amelia Cortés Cotto      F
140          141                 Amador Bonilla Jurado      M
141          142                      Margarita Pineda      F
142          143            Samuel Quintanilla Pedroza      M
143          144                   Esmeralda Sepúlveda      F
144          145                 Jaime Posada Carranza      M
145          146                     Rosalia Ruiz Soto      F
146          147                        Homero Armenta      M
147          148                 Leonardo Zamudio Baca      M
148          149                         Emilia Madera      F
149          150              Citlali Herrera Longoria      F
150          151                 Carla Aguilar Salinas      F
151          152               Delia Ceballos Olivares      F
152          153                        Estela Sanches      F
153          154                Yolanda Moreno Becerra      F
154          155                   Alma Pulido Almaraz      F
155          156           Araceli Marroquín Velásquez      F
156          157               Renato Palacios Perales      M
157          158                Camila Palacios Alonso      F
158          159                   David Rincón Nájera      M
159          160      Marco Antonio Caraballo Guerrero      M
160          161                 Rolando Pacheco Soria      M
161          162                        Leonardo Marín      M
162          163                  Ivonne García Merino      F
163          164               Araceli Segovia Carrera      F
164          165                Nayeli Esquibel Montes      F
165          166               Verónica Cordero Gracia      F
166          167                   Benjamín Concepción      M
167          168               Elvia Delgadillo Zarate      F
168          169                   Vanesa Benítez Díaz      F
169          170                   Miguel Rivera Valle      M
170          171               Marisol Vallejo Medrano      F
171          172               Ignacio Corona Quiñónez      M
172          173                   Mariano Quintanilla      M
173          174                       Hernán Laureano      M
174          175                   Anabel Mora Sarabia      F
175          176                   Horacio Riojas Razo      M
176          177              Ana Luisa Negrete Llamas      F
177          178          Verónica Bustamante Villegas      F
178          179                 Juan Carlos Ríos Vera      M
179          180                   Alma Rascón Vázquez      F
180          181                  Elena Medina Zedillo      F
181          182                         Mónica Corona      F
182          183  María del Carmen Candelaria Montalvo      F
183          184                Natalia de León Arenas      F
184          185                Marcela Quiñones Soria      F
185          186          Santiago Covarrubias Narváez      M
186          187                 Guillermina Ontiveros      F
187          188                   Ivonne Zamora Ávila      F
188          189                  Vicente Mesa Barraza      M
189          190                 Barbara Valdez Olvera      M
190          191                 Flavio Zavala Cornejo      M
191          192             Ariadna Verduzco Cisneros      F
192          193               Horacio Orosco Ceballos      F
193          194                 Arturo Marín Valdivia      F
194          195               Trinidad Méndez Cavazos      F
195          196                          Olivia Cabán      F
196          197                  Yuridia Piña Sauceda      F
197          198                          Aida Naranjo      F
198          199            Dolores Gallegos Mondragón      F
199          200                  Elisa Gastélum Chapa      F

ERROR 8 fechas nacimientos vacias

In [73]:
# Error 8 — verificar y documentar que hay nulos que seria benefico investigarlos (no se modifican)
print(f"Pacientes sin fecha de nacimiento: {pacientes['fecha_nacimiento'].isnull().sum()}")
pacientes[pacientes['fecha_nacimiento'].isnull()][['id_paciente', 'nombre_completo']]

Pacientes sin fecha de nacimiento: 25

     id_paciente             nombre_completo
0              1     Wilfrido Pacheco Urbina
1              2    Alejandro Rentería Bueno
16            17       Elias Zamudio Sauceda
17            18          Celia Barrios Leal
20            21                Ricardo Saiz
36            37               Ángela Gollum
37            38         Susana Loera Gaytán
43            44         Lilia Valles Dueñas
60            61       Verónica Arenas Mares
74            75            Silvano Valentín
88            89     Aurora Galindo Zambrano
95            96     Paola Henríquez Delgado
102          103          Nadia García Armas
113          114  María Cristina Gil Pedraza
116          117    Humberto Herrera Noriega
126          127    Jerónimo Valadez Nazario
129          130        Sessa Valdés Alvarez
131          132       Georgina Mares Mojica
133          134      Claudio Valles Pacheco
134          135       Ángela Collado Angulo
136          137    Lourdes Rendón Mondragón
137          138     Cristina Negrón Marrero
140          141       Amador Bonilla Jurado
161          162              Leonardo Marín
165          166     Verónica Cordero Gracia

ERROR 9 CORREOS EN PACIENTES

In [77]:
# Error 9 — reconstruir correos de pacientes
import unicodedata, re

def quitar_acentos(texto):
    return ''.join(
        c for c in unicodedata.normalize('NFD', texto)
        if unicodedata.category(c) != 'Mn'
    )

def reconstruir_correo_paciente(nombre):
    partes = nombre.split()

    # ignorar partículas comunes
    particulas = {'de', 'del', 'la', 'los', 'las', 'el'}
    partes_filtradas = [p for p in partes if p.lower() not in particulas]

    primer_nombre = quitar_acentos(partes_filtradas[0].lower())

    if len(partes_filtradas) == 2:
        primer_apellido = quitar_acentos(partes_filtradas[1].lower())
    elif len(partes_filtradas) == 3:
        primer_apellido = quitar_acentos(partes_filtradas[1].lower())
    elif len(partes_filtradas) >= 4:
        primer_apellido = quitar_acentos(partes_filtradas[2].lower())
    else:
        primer_apellido = quitar_acentos(partes_filtradas[0].lower())

    return f"{primer_nombre}{primer_apellido}@hospitalvital.mx"

pacientes['correo_electronico'] = pacientes['nombre_completo'].apply(reconstruir_correo_paciente)

In [78]:
pacientes.head(20)

,id_paciente,nombre_completo,fecha_nacimiento,genero,correo_electronico,id_nacionalidad
0,1,Wilfrido Pacheco Urbina,None,F,wilfridopacheco@hospitalvital.mx,10
1,2,Alejandro Rentería Bueno,None,M,alejandrorenteria@hospitalvital.mx,10
2,3,Ignacio Hernádez Mejía,1945-01-07,M,ignaciohernadez@hospitalvital.mx,10
3,4,Karina Serrano Abreu,2018-10-01,F,karinaserrano@hospitalvital.mx,10
4,5,Patricia Ríos,1985-06-26,F,patriciarios@hospitalvital.mx,6
5,6,Ana Escobedo Sisneros,1978-06-25,F,anaescobedo@hospitalvital.mx,10
6,7,Silvia Samaniego Quintanilla,1936-04-07,F,silviasamaniego@hospitalvital.mx,10
7,8,Emilia Jaramillo Ulloa,1947-01-27,F,emiliajaramillo@hospitalvital.mx,10
8,9,Graciela Quezada Rubio,1945-10-08,F,gracielaquezada@hospitalvital.mx,10
9,10,Alicia Grijalva Covarrubias,1971-07-15,F,aliciagrijalva@hospitalvital.mx,10
10,11,Pedro Alcaraz Urías,1984-10-08,M,pedroalcaraz@hospitalvital.mx,10
11,12,Aurelio Garza Carrera,1992-01-17,M,aureliogarza@hospitalvital.mx,10
12,13,Caridad Corrales,1997-01-26,F,caridadcorrales@hospitalvital.mx,2
13,14,Guillermo Saucedo Laboy,1985-10-16,M,guillermosaucedo@hospitalvital.mx,10
14,15,Maximiliano Rodríquez Guerrero,1991-05-30,M,maximilianorodriquez@hospitalvital.mx,10
15,16,Pedro Colunga,1981-06-13,M,pedrocolunga@hospitalvital.mx,10
16,17,Elias Zamudio Sauceda,None,M,eliaszamudio@hospitalvital.mx,10
17,18,Celia Barrios Leal,None,F,celiabarrios@hospitalvital.mx,10
18,19,Linda Molina Sarabia,1965-08-09,F,lindamolina@hospitalvital.mx,10
19,20,Abelardo Leyva Lugo,2009-02-14,M,abelardoleyva@hospitalvital.mx,10

ESPECIALIDADES

In [79]:
espeialidades=pd.read_sql("SELECT * FROM especialidades", engine)
espeialidades

   id_especialidad nombre_especialidad
0                1         Cardiología
1                2           Pediatría
2                3        Dermatología
3                4         Ginecología
4                5          Neurología
5                6           Oncología

In [82]:
espeialidades["nombre_especialidad"].duplicated().any() # no hay nombres duplicados. TOOD OK

np.False_

MEDICAMENTOS

In [83]:
medicamentos=pd.read_sql("SELECT * FROM medicamentos", engine)
medicamentos

,id_medicamento,nombre_medicamento,descripcion
0,1,Paracetamol,Alivia la diarrea.
1,2,Ibuprofeno,Antiinflamatorio no esteroideo utilizado para ...
2,3,Omeprazol,Reduce la producción de ácido en el estómago.
3,4,Amoxicilina,Antibiótico para tratar infecciones bacterianas.
4,5,Loratadina,Alivia síntomas de alergia como estornudos o p...
5,6,Metformina,Ayuda a controlar los niveles de azúcar en san...
6,7,Losartán,Medicamento para controlar la presión arterial.
7,8,Ácido fólico,Suplemento usado para prevenir defectos congén...
8,9,Vitamina D,Contribuye a la absorción de calcio y fortalec...
9,10,Ranitidina,Disminuye la acidez estomacal.
10,11,Cetirizina,Antihistamínico para tratar alergias.
11,12,Salbutamol,Reduce la respiración.
12,13,Diclofenaco,Antiinflamatorio y analgésico para dolor muscu...
13,14,Tramadol,Analgésico opioide para dolor moderado a severo.
14,15,Simvastatina,Reduce el colesterol en sangre.
15,16,Clonazepam,Utilizado para tratar trastornos de ansiedad o...
16,17,Aspirina,"Analgésico, antiinflamatorio y anticoagulante."
17,18,Prednisona,Corticoide para reducir inflamación y tratar a...
18,19,Naproxeno,Alivia dolor de cabeza muy fuerte.
19,20,Azitromicina,Antibiótico para infecciones respiratorias y d...

ERROR 10 DESCRIPCIONES INCORRECTAS EN MEDICAMENTOS

In [84]:
medicamentos.loc[medicamentos['id_medicamento'] == 1, 'descripcion'] = 'Analgésico y antipirético para aliviar el dolor y reducir la fiebre.'
medicamentos.loc[medicamentos['id_medicamento'] == 12, 'descripcion'] = 'Broncodilatador que facilita la respiración en casos de asma o broncoespasmo.'

medicamentos.loc[medicamentos['id_medicamento'].isin([1, 12]), ['nombre_medicamento', 'descripcion']]

   nombre_medicamento                                        descripcion
0         Paracetamol  Analgésico y antipirético para aliviar el dolo...
11         Salbutamol  Broncodilatador que facilita la respiración en...

In [85]:
medicamentos

,id_medicamento,nombre_medicamento,descripcion
0,1,Paracetamol,Analgésico y antipirético para aliviar el dolo...
1,2,Ibuprofeno,Antiinflamatorio no esteroideo utilizado para ...
2,3,Omeprazol,Reduce la producción de ácido en el estómago.
3,4,Amoxicilina,Antibiótico para tratar infecciones bacterianas.
4,5,Loratadina,Alivia síntomas de alergia como estornudos o p...
5,6,Metformina,Ayuda a controlar los niveles de azúcar en san...
6,7,Losartán,Medicamento para controlar la presión arterial.
7,8,Ácido fólico,Suplemento usado para prevenir defectos congén...
8,9,Vitamina D,Contribuye a la absorción de calcio y fortalec...
9,10,Ranitidina,Disminuye la acidez estomacal.
10,11,Cetirizina,Antihistamínico para tratar alergias.
11,12,Salbutamol,Broncodilatador que facilita la respiración en...
12,13,Diclofenaco,Antiinflamatorio y analgésico para dolor muscu...
13,14,Tramadol,Analgésico opioide para dolor moderado a severo.
14,15,Simvastatina,Reduce el colesterol en sangre.
15,16,Clonazepam,Utilizado para tratar trastornos de ansiedad o...
16,17,Aspirina,"Analgésico, antiinflamatorio y anticoagulante."
17,18,Prednisona,Corticoide para reducir inflamación y tratar a...
18,19,Naproxeno,Alivia dolor de cabeza muy fuerte.
19,20,Azitromicina,Antibiótico para infecciones respiratorias y d...

RECETAS

In [86]:
recetas=pd.read_sql("SELECT * FROM recetas", engine)
recetas

    id_receta  id_paciente  id_medico fecha_receta
0           1            5         65   2024-04-28
1           2          179         87   2023-09-20
2           3          111         23   2023-07-02
3           4           28         13   2023-09-02
4           5          135         20   2024-12-04
5           6           62         25   2023-07-15
6           7          159         68   2023-09-29
7           8           65         46   2024-12-02
8           9           69         51   2024-04-16
9          10           21         48   2023-04-19
10         11          104         59   2024-01-04
11         12          145         32   2024-06-02
12         13          179         29   2024-06-16
13         14           77         88   2024-01-10
14         15           21         84   2024-03-27
15         16          167         98   2024-12-13
16         17            9         12   2024-05-31
17         18          104         49   2023-07-08
18         19           97         71   2024-07-17
19         20          122          8   2025-02-13
20         21          164          2   2023-06-04
21         22          180         22   2023-05-20
22         23           22         64   2023-11-25
23         24          112         83   2024-02-02
24         25           85         73   2024-10-06
25         26           25         68   2024-10-08
26         27           11         30   2024-04-04
27         28           55         89   2024-05-11
28         29          146         61   2024-02-12
29         30           70          6   2024-11-16
30         31           20         88   2024-02-11
31         32           72         70   2024-12-28
32         33          145         85   2024-06-18
33         34            9         23   2023-05-26
34         35           81          3   2023-07-05
35         36           54         76   2023-12-01
36         37           37         97   2024-08-09
37         38          183         51   2023-05-26
38         39           20         39   2024-03-13
39         40           42         73   2024-03-25
40         41           62         73   2024-09-08
41         42          100         87   2024-05-04
42         43          139         43   2023-12-22
43         44           99         97   2023-07-07
44         45          190         18   2025-02-08
45         46          177         93   2025-01-01
46         47           21         65   2024-11-25
47         48          191         45   2024-05-31
48         49           14         13   2024-08-07
49         50          112         30   2024-06-28
50         51           20         44   2023-08-18
51         52          155         99   2024-11-15
52         53          158         77   2023-07-08
53         54          102        100   2024-02-29
54         55           84          4   2024-04-23
55         56          163         35   2025-03-06
56         57          116         63   2025-02-01
57         58           59         46   2023-05-12
58         59          142         49   2025-01-03
59         60          111         24   2023-07-04
60         61          175         75   2024-05-05
61         62          170         49   2023-07-26
62         63           22         99   2023-11-21
63         64          159         38   2023-08-04
64         65           64         92   2023-08-02
65         66           19         11   2023-12-05
66         67           69         20   2025-03-25
67         68           98         92   2024-09-30
68         69          163         20   2023-09-21
69         70          190         50   2023-12-23
70         71           82         47   2025-03-29
71         72           28         12   2024-05-06
72         73            2         40   2025-02-22
73         74          114         47   2023-11-05
74         75          195         35   2025-01-15
75         76           27         17   2023-05-30
76         77           23         24   2023-10-10
77         78          111         58   2023-08-29
78         79          143         72   2024-08-04
79         80          132         53   2024-05-30
80         81           27          4   2023-10-29
81         82           23         46   2023-07-05
82         83          142         12   2024-07-27
83         84          153         77   2023-11-20
84         85           84         50   2024-07-19
85         86            4         38   2024-05-17
86         87          106         50   2023-06-10
87         88          200         11   2024-04-23
88         89          186         72   2024-08-08
89         90           63         74   2023-08-07
90         91          134         22   2024-07-01
91         92          176         49   2024-06-23
92         93           44         18   2023-07-27
93         94           69         39   2023-08-09
94         95           69         64   2024-08-22
95         96           38          9   2024-07-27
96         97           43         56   2024-10-09
97         98           71         54   2025-02-27
98         99           77         62   2024-07-12
99        100           20         47   2023-12-17

In [87]:
recetas.isnull().any() # no hay ningun dato null

id_receta       False
id_paciente     False
id_medico       False
fecha_receta    False
dtype: bool

In [92]:
# verificar que todos los id_paciente en recetas existen en pacientes
ids_pacientes = set(pacientes['id_paciente'])
ids_medicos = set(medicos['id_medico'])

recetas_pac_invalidos = recetas[~recetas['id_paciente'].isin(ids_pacientes)]
recetas_med_invalidos = recetas[~recetas['id_medico'].isin(ids_medicos)]

print(f"Recetas con id_paciente inexistente: {len(recetas_pac_invalidos)}")
print(f"Recetas con id_medico inexistente: {len(recetas_med_invalidos)}")

Recetas con id_paciente inexistente: 0
Recetas con id_medico inexistente: 0

RECETAS MEDICAMENTOS

In [88]:
detalles_recetas=pd.read_sql("SELECT * FROM detalles_recetas", engine)
detalles_recetas

     id_detalle  id_receta  id_medicamento       dosis      frecuencia
0             1         33               8       10 ml  Una vez al día
1             2         79               7       10 ml    Cada 8 horas
2             3         18              10   1 tableta   Cada 12 horas
3             4         43              20       10 ml   Cada 12 horas
4             5         57              11       10 ml  Una vez al día
5             6         77               5      500 mg   Cada 12 horas
6             7         78               7       10 ml   Cada 12 horas
7             8         23              13      500 mg   Cada 12 horas
8             9         95              16  2 tabletas   Cada 12 horas
9            10         49               9       10 ml   Cada 12 horas
10           11         15              19  2 tabletas  Una vez al día
11           12         70               6   1 tableta  Una vez al día
12           13         60               7       10 ml   Cada 12 horas
13           14         89               3       10 ml  Una vez al día
14           15         64               5      500 mg    Cada 8 horas
15           16         33               5       10 ml   Cada 12 horas
16           17         10              15       10 ml  Una vez al día
17           18         52              18       10 ml  Una vez al día
18           19          5              12   1 tableta    Cada 8 horas
19           20         99               8      500 mg    Cada 8 horas
20           21         83              20   1 tableta  Una vez al día
21           22         83              13      500 mg   Cada 12 horas
22           23         14               1   1 tableta   Cada 12 horas
23           24         29              17  2 tabletas   Cada 12 horas
24           25         48              13       10 ml  Una vez al día
25           26         76              17  2 tabletas   Cada 12 horas
26           27          4              16   1 tableta   Cada 12 horas
27           28         54               3   1 tableta  Una vez al día
28           29         19              12      500 mg   Cada 12 horas
29           30         59               7       10 ml   Cada 12 horas
30           31         61               4       10 ml  Una vez al día
31           32         90              15      500 mg    Cada 8 horas
32           33         39               2   1 tableta    Cada 8 horas
33           34         44               4  2 tabletas  Una vez al día
34           35         32              17  2 tabletas  Una vez al día
35           36         21              11       10 ml   Cada 12 horas
36           37         30              13  2 tabletas    Cada 8 horas
37           38         82              14       10 ml    Cada 8 horas
38           39         95              20  2 tabletas   Cada 12 horas
39           40         76              14       10 ml    Cada 8 horas
40           41         91               7  2 tabletas   Cada 12 horas
41           42         97               3   1 tableta  Una vez al día
42           43         24              12      500 mg    Cada 8 horas
43           44         59               4      500 mg  Una vez al día
44           45         63              17      500 mg  Una vez al día
45           46         50              20       10 ml  Una vez al día
46           47         15              12      500 mg   Cada 12 horas
47           48         80               6      500 mg  Una vez al día
48           49         76               3  2 tabletas   Cada 12 horas
49           50         16               8      500 mg    Cada 8 horas
50           51         24              12  2 tabletas  Una vez al día
51           52         50              14  2 tabletas  Una vez al día
52           53         50              14  2 tabletas   Cada 12 horas
53           54         82              18  2 tabletas  Una vez al día
54           55         22              16      500 mg    Cada 8 horas
55           56         24              11       10 ml  Una vez al día
56           57          7              12   1 tableta   Cada 12 horas
57           58         18               7       10 ml  Una vez al día
58           59         65              16       10 ml  Una vez al día
59           60         63              14       10 ml   Cada 12 horas
60           61         22               3   1 tableta    Cada 8 horas
61           62         38               2      500 mg    Cada 8 horas
62           63         69              10  2 tabletas   Cada 12 horas
63           64         73              16   1 tableta  Una vez al día
64           65         15               9      500 mg  Una vez al día
65           66         97               2       10 ml  Una vez al día
66           67         28              14   1 tableta  Una vez al día
67           68         84               8      500 mg    Cada 8 horas
68           69         58               9      500 mg    Cada 8 horas
69           70         57               4  2 tabletas    Cada 8 horas
70           71         95              19      500 mg  Una vez al día
71           72         79              14  2 tabletas  Una vez al día
72           73         18               7  2 tabletas    Cada 8 horas
73           74         73              12      500 mg  Una vez al día
74           75         69               6      500 mg  Una vez al día
75           76         38              10      500 mg  Una vez al día
76           77         87               4  2 tabletas   Cada 12 horas
77           78          8               9  2 tabletas  Una vez al día
78           79         17               8  2 tabletas  Una vez al día
79           80         42               8       10 ml   Cada 12 horas
80           81         19              19      500 mg  Una vez al día
81           82         54              13       10 ml    Cada 8 horas
82           83         82               3       10 ml  Una vez al día
83           84         96               9      500 mg   Cada 12 horas
84           85         63              11   1 tableta  Una vez al día
85           86         12              15      500 mg    Cada 8 horas
86           87         69              13  2 tabletas   Cada 12 horas
87           88         28              16      500 mg   Cada 12 horas
88           89         37              11  2 tabletas  Una vez al día
89           90         63              11   1 tableta    Cada 8 horas
90           91         13              15   1 tableta    Cada 8 horas
91           92         21              15       10 ml    Cada 8 horas
92           93         55               7  2 tabletas  Una vez al día
93           94         39               6      500 mg    Cada 8 horas
94           95         84              12      500 mg    Cada 8 horas
95           96         48               6   1 tableta   Cada 12 horas
96           97         81              10  2 tabletas   Cada 12 horas
97           98         84               3   1 tableta    Cada 8 horas
98           99         28              16   1 tableta    Cada 8 horas
99          100         76               8       10 ml    Cada 8 horas
100         101          2              11   1 tableta   Cada 12 horas
101         102         89               5       10 ml    Cada 8 horas
102         103         30              13   1 tableta  Una vez al día
103         104         14               4      500 mg   Cada 12 horas
104         105         39               5       10 ml    Cada 8 horas
105         106         83               5   1 tableta  Una vez al día
106         107         73               1  2 tabletas   Cada 12 horas
107         108         45               7  2 tabletas   Cada 12 horas
108         109         79              15  2 tabletas    Cada 8 horas
109         110         13               5   1 tableta  Una vez al día
110         111         94              13      500 mg   Cada 12 horas
111         112         41               5  2 tabletas   Cada 12 horas
112         113         83               3  2 tabletas  Una vez al día
113         114         77              20      500 mg  Una vez al día
114         115          4              10  2 tabletas  Una vez al día
115         116         78              17  2 tabletas  Una vez al día
116         117         51              10   1 tableta    Cada 8 horas
117         118         64              13   1 tableta    Cada 8 horas
118         119         64              20   1 tableta  Una vez al día
119         120          2              12      500 mg    Cada 8 horas
120         121         50              19       10 ml   Cada 12 horas
121         122         70               6       10 ml    Cada 8 horas
122         123          3              19   1 tableta    Cada 8 horas
123         124         34               7   1 tableta    Cada 8 horas
124         125         51              17      500 mg  Una vez al día
125         126         92              17       10 ml   Cada 12 horas
126         127         90              13   1 tableta  Una vez al día
127         128         69              18  2 tabletas   Cada 12 horas
128         129         11              10   1 tableta  Una vez al día
129         130         27               5      500 mg   Cada 12 horas
130         131         76               3      500 mg  Una vez al día
131         132         56               8   1 tableta    Cada 8 horas
132         133         12              14   1 tableta   Cada 12 horas
133         134         79              20   1 tableta   Cada 12 horas
134         135         86               6   1 tableta    Cada 8 horas
135         136         91               5   1 tableta    Cada 8 horas
136         137         64              12      500 mg    Cada 8 horas
137         138         48               5      500 mg  Una vez al día
138         139         16               1      500 mg   Cada 12 horas
139         140         35              17   1 tableta   Cada 12 horas
140         141         92              19   1 tableta   Cada 12 horas
141         142         59              17      500 mg    Cada 8 horas
142         143         64              19  2 tabletas   Cada 12 horas
143         144         21               9   1 tableta  Una vez al día
144         145         87               4  2 tabletas  Una vez al día
145         146         66               1   1 tableta    Cada 8 horas
146         147         32               2       10 ml   Cada 12 horas
147         148         50               5  2 tabletas    Cada 8 horas
148         149         71              14  2 tabletas   Cada 12 horas
149         150         32              14      500 mg   Cada 12 horas

In [89]:
detalles_recetas.isnull().any() # no hay nulos

id_detalle        False
id_receta         False
id_medicamento    False
dosis             False
frecuencia        False
dtype: bool

In [91]:
ids_recetas = set(recetas['id_receta'])
ids_medicamentos = set(medicamentos['id_medicamento'])

det_receta_invalidos = detalles_recetas[~detalles_recetas['id_receta'].isin(ids_recetas)]
det_med_invalidos = detalles_recetas[~detalles_recetas['id_medicamento'].isin(ids_medicamentos)]

print(f"Detalles con id_receta inexistente: {len(det_receta_invalidos)}")
print(f"Detalles con id_medicamento inexistente: {len(det_med_invalidos)}")

Detalles con id_receta inexistente: 0
Detalles con id_medicamento inexistente: 0